### ISSUE TITLE
Convert SpeakerID from a Text Element to a custom Unique ID element

### ISSUE THREAD

**Issue by kentico-michaelb** [kentico-michaelb/kontent-sample-app-conference-net#2]
### Motivation

When creating Speakers for the conference, there are no protections against editors inputting duplicate SpeakerIDs.  If two speakers have the same ID, the application currently pulls whichever speaker appears first in the JSON repsonse.

### Proposed solution

Implement the Unique Textbox custom element from: https://kentico.github.io/kontent-custom-element-samples/gallery/#unique-textbox to ensure entered text is unique.

### Additional context

It may be worthwhile to extend the custom element to automatically generate IDs instead of having content editors manually enter the ID.

**Comment by pokornyd** [comment]
basically finished, the code is not so pretty and calls for some refactoring but it does the job. source code of the element can be found here: https://github.com/pokornyd/pokornyd.github.io/blob/master/unique_text.html and this is the URL that is targeted by the element in Kontent: https://pokornyd.github.io/unique_text.html so I'm not entirely sure how to go about moving it into our repo. thoughts?
