### ISSUE TITLE
Speakers' session links do not work

### ISSUE THREAD

**Issue by kentico-michaelb** [kentico-michaelb/kontent-sample-app-conference-net#26]
### Brief bug description

Anchor element surrounding "session" items has no src attribute.

### Repro steps

1. Go to ~/Speakers
2. Click on Aaron Collier
3. Click on "Patterson companies..." or "Why should I..."

### Expected behavior

Redirect to the Agenda Item referenced in the Sessions section.

**Comment by matus-usiak** [comment]
Is there actually a page for the session itself? For example when I go to ~/location/Agenda/urlSlugOfAgendaItem - https://konnections.herokuapp.com/Denver/Agenda/patterson-companies-implementing-kentico-headless-for-an-enterprise-level-customer
I get a 404

**Comment by kentico-michaelb** [comment]
Detail method from Agenda controller was accidentally removed in : https://github.com/kentico-michaelb/kontent-sample-app-conference-net/commit/ace846eb3e6f21786c89e31803797110bd38ffb8#diff-42cfab857c4d282515261c14ba9ee493

Re-added in push to master branch: https://github.com/kentico-michaelb/kontent-sample-app-conference-net/commit/39e4b85758bf4c4b251495046c88b3560afb8f74
